# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2024-04-11 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0008_auto_20171106_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='workout_images/'),
        ),
    ]
