# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2024-04-11 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0011_auto_20240411_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='image_blob',
        ),
        migrations.AddField(
            model_name='workout',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='workout_images/'),
        ),
    ]
